### ISSUE TITLE
Project cannot compile on branch step052

### ISSUE THREAD

**Issue by lucasebana** [eliemichel/LearnWebGPU-Code#1]
Hello!
I'm running Ubuntu 22.04, I tried to build the project on branch step052, using the command in the readme, but I get the following error : 

> cmake . -B build
-- Using X11 for window creation
-- Configuring done
CMake Error in webgpu/CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "webgpu".
CMake Error in webgpu/CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "webgpu".
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by eliemichel** [comment]
Hi Lucas,

Did you close this issue because it ended up working? Otherwise I just updated the branch could you check again?

FTR this repository holds the hopefully most up to date content of the `webgpu/` dist: https://github.com/eliemichel/WebGPU-binaries

**Comment by lucasebana** [comment]
Hello,
Oh I'm sorry I closed the issue mistakenly. The first error is gone but now there's an issue with the second command : 

```
$ cmake --build build
...
[ 95%] Building CXX object CMakeFiles/App.dir/main.cpp.o
/home/lucas/misc/prog/webgpu/LearnWebGPU-Code/main.cpp: In function ‘int main(int, char**)’:
/home/lucas/misc/prog/webgpu/LearnWebGPU-Code/main.cpp:235:40: error: lvalue required as unary ‘&’ operand
  235 |         layoutDesc.bindGroupLayouts = &(WGPUBindGroupLayout)bindGroupLayout;
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by eliemichel** [comment]
Can you try either

    layoutDesc.bindGroupLayouts = &((WGPUBindGroupLayout)bindGroupLayout);

or

    layoutDesc.bindGroupLayouts = (WGPUBindGroupLayout*)&bindGroupLayout;

I have mostly tested on Windows so far, sorry that you are the one going through these compiler difference details, shouldn't be a showstoper though! I'll eventually set up some continuous integration like I did [here](https://github.com/eliemichel/glfw3webgpu/actions).
