### ISSUE TITLE
step 30 vanilla is giving shader compilation error

### ISSUE THREAD

**Issue by prashant-saxena** [eliemichel/LearnWebGPU-Code#15]
Hello,
Windows 10
wgpu_native.dll

When building and running [step30](https://github.com/eliemichel/LearnWebGPU-Code/tree/step030-vanilla), The error callback is showing vertex shader source and a message:
 ```
no definition in scope for identifier: 'vec2f'
```
I tried searching on google but it seems there is not much info is available. Although it's compiling and running fine on [online](https://takahirox.github.io/online-wgsl-editor/index.html)
webgpu shader compiler.

**Comment by prashant-saxena** [comment]
The error is gone when switching to the latest version (0, 16, 2, 1)

**Comment by eliemichel** [comment]
Yes old versions of naga/wgpu-native did not support type aliases but this has been fixed for ~6 months now ;)
