### ISSUE TITLE
step034 should use `uint16_t` in index buffer size computation

### ISSUE THREAD

**Issue by razcore-rad** [eliemichel/LearnWebGPU-Code#18]
https://github.com/eliemichel/LearnWebGPU-Code/blob/8d687d12742d0c0faf54ea1dc6f5ac2546f555a6/main.cpp#L254 should be:

```cpp
bufferDesc.size = indexData.size() * sizeof(uint16_t);
```

**Comment by sleeplessai** [comment]
@razcore-rad 
No, an uint16_t data should also be aligned as 4-bytes. sizeof(float) is correct. Please check the webgpu data alignment document for more certain details.

**Comment by eliemichel** [comment]
@razcore-rad is actually right, although as @sleeplessai data must be 4-byte aligned, allocating `indexData.size() * sizeof(float)` is not just aligning, it rather allocate twice as much memory as we need.

`bufferDesc.size = indexData.size() * sizeof(uint16_t)` is correct, provided there is an even number of indices (as noted in the guide's body). Thanks for reporting!
