### ISSUE TITLE
A First Vertex Attribute wrong url from the WebGPU Guide

### ISSUE THREAD

**Issue by felipunky** [eliemichel/LearnWebGPU-Code#22]
This is the correct one: https://github.com/eliemichel/LearnWebGPU-Code/blob/step032/main.cpp I think.

**Comment by eliemichel** [comment]
The README was not right but the link is pointing to the right branch! Thanks for reporting teh inconsistency.

**Comment by felipunky** [comment]
Thanks for the tutorials BTW!
