### ISSUE TITLE
Unable to run screen capture

### ISSUE THREAD

**Issue by MPcoreDev** [eliemichel/LearnWebGPU-Code#25]
Thanks for the great work.  

I am trying to capture one frame to file. I follow the steps from https://eliemichel.github.io/LearnWebGPU/advanced-techniques/screen-capture.html but I can't make it run. It builds fine but at runtime I have the following error:  

```
Uncaptured device error: type 1 [Texture "of [SwapChain]"] usage (TextureUsage::RenderAttachment) doesn't include TextureUsage::TextureBinding.
 - While validating entries[0] as a Texture.
Expected entry layout: { binding: 0, visibility: ShaderStage::Fragment, texture: { sampleType: TextureSampleType::Float, viewDimension: TextureViewDimension::e2D, multisampled: 0 } }
 - While validating [BindGroupDescriptor] against [BindGroupLayout]
 - While calling [Device].CreateBindGroup([BindGroupDescriptor]).
```

Do I need to change the swapchain texture usage?  
My swapchain is initialized like this:  
```
wgpu::SwapChainDescriptor swapChainDesc {
                .usage = wgpu::TextureUsage::RenderAttachment,
                .format = wgpu::TextureFormat::BGRA8Unorm,
                .width = _rendererDesc.width,
                .height = _rendererDesc.height,
                .presentMode = wgpu::PresentMode::Fifo
        };
```

I tried to add the flag `wgpu::TextureUsage::TextureBinding` to the usage but It sill does not work. It raises this error:  
```
Uncaptured device error: type 1 Usage (TextureUsage::(TextureBinding|RenderAttachment)) is not TextureUsage::RenderAttachment, which is (currently) the only accepted usage. Other usage flags require enabling FeatureName::SurfaceCapabilities
 - While validating [SwapChainDescriptor]
 - While calling [Device].CreateSwapChain([SwapChainDescriptor]).
```

I am using dawn on windows with msvc2022.

**Comment by eliemichel** [comment]
Yeah this is infortunate, what I end up doing in practice is render to another texture to save the image (and just copy it to the swap chain's texture view). This way I can use the `saveTexture` function of the `save_image.h` file instead of `saveTextureView`.

Anyways this chapter needs some refreshing ^^

**Comment by MPcoreDev** [comment]
Thank you for the reply. I just ended up with a similar implementation.  
For the frame I want to capture, instead of getting the nexttexture from the swapchain, I build a new texture with the same attributes and with the usage flags `TextureUsage::RenderAttachment | TextureUsage::CopySrc` then after I rendererd to it I use `saveTexture`. Technically I therefore losse this frame on screen, which is not important in my use case.
