### ISSUE TITLE
Question about glm integration

### ISSUE THREAD

**Issue by MPcoreDev** [eliemichel/LearnWebGPU-Code#27]
I can see the following in the code:   
`m_uniforms.viewMatrix = glm::lookAt(vec3(-2.0f, -3.0f, 2.0f), vec3(0.0f), vec3(0, 0, 1));`  

I wonder why the up vector is (0, 0, 1) instead of (0, 1, 0) ?

(Note that some other examples are using (0, 1, 0) like [here](https://github.com/samdauwe/webgpu-native-examples/blob/3c4b59e1fbac3dc8913f8de5163de438f601e130/src/examples/a_buffer.c#L50))

**Comment by MPcoreDev** [comment]
In fact that works also as exptexted with (0, 1, 0). That was just a choice.   
My bad !

**Comment by eliemichel** [comment]
There is no consensus about which of the Y (`0,1,0`) or Z (`0,0,1`) should be used as the vertical axis, the choice is left to you!

For instance Blender, Unreal Engine and this guide use Z-up, Maya and Unity use Y-up, etc.
