### ISSUE TITLE
[Suggestion] step-095: tie ImGui and WebGPU

### ISSUE THREAD

**Issue by ypujante** [eliemichel/LearnWebGPU-Code#36]
First, thank you very much for your tutorial. This is very helpful.

Second, I do not have any issue running step-095 on macOS unlike another user.

I wanted to suggest a small change in the example which allow for changes in ImGui to affect the result. Simply changing the clear color like this:

```cpp
// moved outside (color corresponds to Color{ 0.05, 0.05, 0.05, 1.0 } in ImVec4 format)
static ImVec4 clear_color = ImVec4(63.f/255.f, 63.f/255.f, 63.f/255.f, 1.00f);
inline float gammaCorrect(float f) { return std::pow(f, 2.2f); }

//....
renderPassColorAttachment.clearValue = Color{ gammaCorrect(clear_color.x), gammaCorrect(clear_color.y), gammaCorrect(clear_color.z), clear_color.w };
```

When you change the color in ImGui it changes the background color. Also note that the color needs to be gamma corrected since the correction is not happening in the shader...

**Comment by eliemichel** [comment]
Gamma correction has been bothering me for a long time. The required correction actually **depends on the swap chain format**, and in particular the preferred format returned by `wgpu-native` and `Dawn` have different gamma correction needs (on Windows at least). I'm considering introducing [this utility function](https://github.com/eliemichel/WebGPU-utils/blob/main/c/wgpuTextureFormatGamma.c) from the very beginning, but it makes things a bit verbose.

**Comment by eliemichel** [comment]
The preferred format is by definition not something we should expect all implementations to agree on, that's actually there is a function to query it on runtime (it does not only depend on the implementation, but rather the OS or whatever context is providing teh surface we draw on). It is more reasonable to expect that a set of utility functions emerges as a standard enough companion of the official `webgpu.h` spec.
