### ISSUE TITLE
Handling window resize with new WebGPU API

### ISSUE THREAD

**Issue by IgorAlexey** [eliemichel/LearnWebGPU-Code#43]
This feels like an extremely fundamental problem, but since the swapchain was gunned down, I've been continually getting segmentation errors when attempting to reimplement resize

The related resources I've found, haven't proven applicable to C++

• [Reddit](https://www.reddit.com/r/rust_gamedev/comments/1dincvn/how_to_solve_problem_of_window_resizing_with_wgpu/) • [sotrh.github.io](https://sotrh.github.io/learn-wgpu/beginner/tutorial2-surface/#state-new)

It seems like they can simply unconfigure the surface, replace dimensions in surface config and reconfigure.

However, GLFW appears to be destroying the surface in a resize? Getting another surface with 'glfwGetWGPUSurface' worked previously but not in this version.

**Comment by eliemichel** [comment]
Which backend do you use (dawn or wgpu-native)? I never had to re-query the surface when resizing, I believe you shouldn't need to call glfwGetWGPUSurface again.

**Comment by IgorAlexey** [comment]
Hi @eliemichel! I'm using wgpu-native

**Comment by eliemichel** [comment]
SOrry for the late reply: here is a variant of step30 that supports resizing: [`step030-resize`](https://github.com/eliemichel/LearnWebGPU-Code/tree/step030-resize). Tested with wgpu-native on Windows, let me know if it works for you, and if it does not please share a detailed log!
