### ISSUE TITLE
Missing `step075-vanilla` branch?

### ISSUE THREAD

**Issue by phronmophobic** [eliemichel/LearnWebGPU-Code#48]
I'm having trouble finding the code example for the vanilla version of https://eliemichel.github.io/LearnWebGPU/basic-3d-rendering/texturing/loading-from-file.html. Sorry if I'm overlooking something stupid.

Thanks so much for this project! It's a lifesaver!

**Comment by eliemichel** [comment]
Yep sorry Vanilla branches are not all ready, I put the priority on non-vanilla ones at the time. In the ongoing wave of update (currently at step037) I try to systematically provide it though. Any particular reason why you need to consult this one in particular that I could help with?

**Comment by phronmophobic** [comment]
I was trying to figure out how to get texturing working. It's a little easier to follow the full examples than to try and combine all the snippets from the post, but I figured it out.

The reason I'm interested in the vanilla branch is that I'm writing a [clojure wrapper](https://github.com/phronmophobic/clj-webgpu) which uses webgpu-native as a shared library.

This project has been super helpful! I guess I'll close this issue for now since the vanilla versions are still in progress. Thanks again!
