### ISSUE TITLE
Step095-emscripten Webassembly Issue

### ISSUE THREAD

**Issue by Roy23011** [eliemichel/LearnWebGPU-Code#56]
Hello,

I downloaded the code from the following GitHub repository: LearnWebGPU-Code (step095-emscripten) https://github.com/eliemichel/LearnWebGPU-Code/tree/step095-emscripten              

int main(int, char**) {
	Application app;
	app.onInit();
	std::cout<<"After onInit function :: "<<std::endl;

#ifdef __EMSCRIPTEN__
	std::cout<<"Inside emcripten condition :: "<<std::endl;
	emscripten_set_main_loop_arg(
		[](void *userData) {
			Application& app = *reinterpret_cast<Application*>(userData);
			std::cout<<"Before calling onFrame function :: "<<std::endl;
			app.onFrame();
			std::cout<<"After calling onFrame function :: "<<std::endl;
		},
		(void*)&app,
		0, true
	);
	std::cout<<"After emscripten_set_main_loop_arg function :: "<<std::endl;
#endif 
	return 0;
}

After building the WebGPU project in WebAssembly, I encountered an error after printing “After calling onFrame function” cout message from the above code, getting error as shown on the screen while browsing to http://localhost:8000/App.html. 

How can I fix this error? 
Could anyone please help me with this?
<img width="2195" alt="WebAssemblyIssue" src="https://github.com/user-attachments/assets/6962c373-989d-4651-9c52-7877ce4a34c6">

**Comment by Roy23011** [comment]
@eliemichel  Thanks It's working now after adding depthSlice in the WGPURenderPassColorAttachment object.

**Comment by eliemichel** [comment]
Ok, fixed in [80d032f](https://github.com/eliemichel/LearnWebGPU-Code/commit/80d032f01a7bbb4f6c5b4d15ec7027a1b4477843) then!
