### ISSUE TITLE
Cannot build the initial library code

### ISSUE THREAD

**Issue by m3rashid** [eliemichel/LearnWebGPU-Code#58]
I am on step `step028` and I cannot build the library code, generate so far

I have followed all the steps so far but still can't get the code working. Here I attach the build logs. Please suggest how to sovle this, what could have gone wrong ?

![image](https://github.com/user-attachments/assets/e6f6285a-05ed-43e1-b424-656bcc270a31)

**Comment by eliemichel** [comment]
Hello, GLFW has some dependencies when building on linux, the list of which you may find here: https://www.glfw.org/docs/3.3/compile.html#compile_deps

In your case, you seem to be missing `libwayland-dev`, and possibly `libxkbcommon-dev`. If you want to disable the use of Wayland, you can set `-DGLFW_USE_WAYLAND=0` when invoking CMake.

**Comment by m3rashid** [comment]
Thanks a lot @eliemichel. I missed this part earlier
