### ISSUE TITLE
step010: adapter NotFound

### ISSUE THREAD

**Issue by rollschild** [eliemichel/LearnWebGPU-Code#7]
Hi,

I'm on [step010](https://github.com/eliemichel/LearnWebGPU-Code/tree/step010). After build succeeded I ran into this error when running the executable (with my custom logging):
```
WGPU instance: 0x417ed0
init!
window:0x426060
surface: 0x47c2b0
Requesting adapter...
Could NOT get WebGPU adapter: NotFound
Got adapter: 0
thread '<unnamed>' panicked at 'invalid AdapterId', src/lib.rs:186:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
[1]    28012 IOT instruction (core dumped)  ./build/src/App
```

Basically the error is `Could NOT get WebGPU adapter: NotFound`. So it successfully initialized window, found the surface, but somehow an adapter could not be found/initialized?

I'm using `wgpu-native`, built for Wayland on an Intel graphics laptop. I'm not sure whether it's my code (basically same as yours), or Wayland, or `wgpu-native`, or the graphics card itself is causing this error. Any help would be greatly appreciated. Thank you!

**Comment by eliemichel** [comment]
Okey the problem is that I did not wire Wayland up properly in glfw3webgpu, but there is an easy fix: in [`glfw3webgpu.c` line 47](https://github.com/eliemichel/LearnWebGPU-Code/blob/step010/glfw3webgpu/glfw3webgpu.c#L47) switch the default `WGPU_TARGET` to `WGPU_TARGET_LINUX_WAYLAND` instead if `WGPU_TARGET_LINUX_X11`.

Sorry I did not spend time looking for a way to automate this because [once this is integrated in upstream GLFW](https://github.com/glfw/glfw/pull/2333) I can use GLFW macros (well actually I could use them already, btu hopefully it will soon get merged to I'll do an update of all branches when that happens).

**Comment by rollschild** [comment]
Hey @eliemichel thanks for the quick reply! However I already changed `WGPU_TARGET` to `WGPU_TARGET_LINUX_WAYLAND` myself because otherwise it wouldn't compile. `cmake` build would give me errors. The `adapter NotFound` error happens _after_ I made the change, during runtime.

**Comment by eliemichel** [comment]
Does the adapter initialize well if you don't specify a surface? (`adapterOpts.compatibleSurface = nullptr;`)

**Comment by rollschild** [comment]
@eliemichel Hey, somehow it works now. Not sure what changed, but it's very likely because I pulled in Vulkan dependencies like I did [here](https://github.com/eliemichel/WebGPU-distribution/issues/7#issuecomment-1539234740). 

Surprisingly, when enumerating adapter features, `wgpu-native`'s output is tidier than `dawn`. Here is the features output I got using `wgpu-native`:
```
Adapter features:
 - 1
 - 2
 - 3
 - 4
 - 5
 - 6
 - 7
 - 8
 - 9
 - 1610612737
 - 1610612738
 - 1610612739
 - 1610612740
 - 1610612741
```
and those large numbers at the bottom also differ from the `1002`s I got from `dawn`. Also, there is no warning here, though I got [warnings](https://github.com/eliemichel/WebGPU-distribution/issues/7#issuecomment-1539234740) using `dawn`.

**Comment by rollschild** [comment]
Closing this issue since issue fixed. Thanks!

**Comment by eliemichel** [comment]
These large numbers are backend-specific features. They are intentionnally starting at different offsets to avoid conflict, more details [here](https://eliemichel.github.io/LearnWebGPU/appendices/custom-extensions.html) ;)
