### ISSUE TITLE
Could not get WebGPU adapter: LimitsExceeded

### ISSUE THREAD

**Issue by danvas** [eliemichel/LearnWebGPU-Code#8]
https://github.com/eliemichel/LearnWebGPU-Code/blob/f84c28fcc7710013faddede13c3bd225a31b9ce9/main.cpp#LL87C31-L87C31

Hi Élie, thanks for your tutorial on WebGPU! I've been going through the steps, and I found that I get the following error (on macOS 13.3, Xcode 14.3) at runtime:
```
Requesting adapter...
Got adapter: <wgpu::Adapter 0x7f8f7af06600>
Requesting device...
Could not get WebGPU adapter: LimitsExceeded(FailedLimit { name: "min_uniform_buffer_offset_alignment", requested: 64, allowed: 256 })
Got device: <wgpu::Device 0x0>
adapter.maxVertexAttributes: 31
thread '<unnamed>' panicked at 'invalid DeviceId', src/lib.rs:210:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
[1]    6198 abort      build/Debug/App
```
When I comment out line 87 `deviceDesc.requiredLimits = &requiredLimits;`, it runs fine.
Can you help me figure out this issue?

**Comment by JarWarren** [comment]
Also encountering this issue on macOS 13.3 using wgpu-native, clang and C. Verified that all of my `requiredLimits` were within the supported limits.

Looks like this might be an issue with wgpu? I haven't tried Dawn.

**Comment by eliemichel** [comment]
Do not copy all adapter limits to the device limit, this defeats the prupose of having a limit management mechanism (and if this is really what you want, then just set the device limits to nullptr in the device descriptor ;) ). If you do so, you open the door to the "it works on my hardware" problem where you cannot reproduce your user's issues.

Forwarding limit does make sense for the 2 of them that start with "min" though, so in this very case:

```
deviceLimits.minUniformBufferOffsetAlignment = adapterLimits.minUniformBufferOffsetAlignment;
```

Sorry I forgot it it should indeed be in the example code! I'll leave this issue open to remaind me to do it.

**Comment by danvas** [comment]
Why does it make sense to forward the two "min*" limits in this case?
Anyway, your suggestion fixed the issue on my end. I added this to line 83:
`requiredLimits.limits.minUniformBufferOffsetAlignment = supportedLimits.limits.minUniformBufferOffsetAlignment;`

Thanks for your quick reply and your help!

**Comment by eliemichel** [comment]
Fixed up to `step044`, next steps are WIP for many other reasons!
